### ISSUE TITLE
Timeout repair task tries to complete the Repair task and this leads to crash in PatchOrchestrationApplication

### ISSUE THREAD

**Issue by khandelwalbrijesh** [microsoft/Service-Fabric-POA#25]
TimeoutRepairTask in coordinator Service tries to complete the repair task from Executing state to Completed state. This operation is not supported by repair manager and this leads to crash in Coordinator Service
Application: CoordinatorService.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: RunAsync failed due to an unhandled exception causing the host process to crash: System.InvalidOperationException: The state transition is not allowed: (Executing,Completed) ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071BFD
   at System.Fabric.Interop.NativeClient.IFabricRepairManagementClient2.EndUpdateRepairExecutionState(IFabricAsyncOperationContext context)
   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.PatchOrchestration.CoordinatorService.RepairManagerHelper.<UpdateRepairTaskState>d__36.MoveNext() in D:\a\1\s\src\PatchOrchestrationApplication\CoordinatorService\src\RepairManagerHelper.cs:line 709
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.PatchOrchestration.CoordinatorService.RepairManagerHelper.<TimeoutRepairTasks>d__35.MoveNext() in D:\a\1\s\src\PatchOrchestrationApplication\CoordinatorService\src\RepairManagerHelper.cs:line 635
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.PatchOrchestration.CoordinatorService.CoordinatorService.<RunLoopAsync>d__9.MoveNext() in D:\a\1\s\src\PatchOrchestrationApplication\CoordinatorService\src\CoordinatorService.cs:line 109
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.PatchOrchestration.CoordinatorService.CoordinatorService.<RunAsync>d__8.MoveNext() in D:\a\1\s\src\PatchOrchestrationApplication\CoordinatorService\src\CoordinatorService.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Runtime.StatefulServiceReplicaAdapter.<ExecuteRunAsync>d__23.MoveNext()
Stack:
   at System.Environment.FailFast(System.String)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by khandelwalbrijesh** [comment]
Fixed in Version v1.4.1 of the appllication.
Link: https://github.com/microsoft/Service-Fabric-POA/releases/tag/v1.4.1

**Comment by khandelwalbrijesh** [comment]
Mitigations for this issue could be:
 Find out the repair task stuck of the deleted node which is stuck in executing state. You would find it in the warning on Patch orchestration application. Then, use below command to fix:
Stop-ServiceFabricRepairTask -TaskId <TaskID>
OR
Do an unmonitoredAuto upgrade to v1.4.1
