### ISSUE TITLE
POA reporting invalid DateTime setting after upgrade to 1.4.1

### ISSUE THREAD

**Issue by krawls19** [microsoft/Service-Fabric-POA#29]
After upgrading to 1.4.1 the POA keeps reporting this error. I upgraded POA to 1.4.1 on our beta cluster and this has not had a problem. I tried rolling back to 1.3.2 and the error remains now. I've unprovisioned the type and tried a clean deploy with the same warning. The only setting overridden was the WUFrequency to run "Daily,14:00:00".

Warning
 'Patch Orchestration Node Agent Service' reported Warning for property 'WUOperationSetting-_sfsandbox_0'.
Exception while starting timer. System.FormatException: String was not recognized as a valid DateTime.
   at Microsoft.ServiceFabric.PatchOrchestration.NodeAgentNTService.Manager.TimerManager.ReadCheckpointFile() in D:\a\1\s\src\PatchOrchestrationApplication\NodeAgentNTService\src\Manager\TimerManager.cs:line 453
   at Microsoft.ServiceFabric.PatchOrchestration.NodeAgentNTService.Manager.TimerManager.LoadSettings() in D:\a\1\s\src\PatchOrchestrationApplication\NodeAgentNTService\src\Manager\TimerManager.cs:line 376
   at Microsoft.ServiceFabric.PatchOrchestration.NodeAgentNTService.Manager.TimerManager.StartTimer() in D:\a\1\s\src\PatchOrchestrationApplication\NodeAgentNTService\src\Manager\TimerManager.cs:line 64

**Comment by khandelwalbrijesh** [comment]
Hi Krawls, 
Could you log into the same machine and in the 'D' directory(PatchOrchestrationApplication named folder), try to search the TimerCheckPoint.txt and paste the contents here?

**Comment by khandelwalbrijesh** [comment]
@krawls19, Please let us know if you are still facing this issue.

**Comment by krawls19** [comment]
It looks like the health state for that service was stuck and not cleared. I recreated the application with a different name and have not had an issue. So it was probably a transient thing that got stuck being reported as unhealthly. Thanks.
